### PR TITLE
Add perl template

### PR DESCRIPTION
**Pull request by zeerorg**
Signed-off-by: Rishabh Gupta <r.g.gupta@outlook.com>

This PR adds perl template to the repository

To try it out you can do:

```bash
faas-cli template pull https://github.com/zeerorg/perl-template
faas-cli new --lang perl <fn-name>
```

### CODE REVIEW

**Comment by alexellis** [comment]
I think Derek has a typo :) please can you write his file in a separate PR?

**Comment by alexellis** [comment]
That will then enable Derek we can use it to validate that the commits are Signed-off

**Comment by alexellis** [comment]
Please could you squash these if it's not too much trouble for you

**Comment by zeerorg** [comment]
Done 👍

**Pull request merged**
